export interface Event {
  name: string;
  date: string;
  location: string;
  tags: string[];
  image: string;
  link: string;
}

export const upcomingEvents: Event[] = [
  {
    name: "DeCaF Winter 2026",
    date: "January 20th, 2026",
    location: "Price Center West Ballroom A",
    tags: ["Career"],
    image: "/event-logos/decaf-event-wi26.png",
    link: "https://decafatucsd.com/",
  },
];
export const pastEvents: Event[] = [
  {
    name: "Engineers on the Green",
    date: "January 8th, 2026",
    location: "Warren Mall",
    tags: ["Social", "Career"],
    image: "/event-logos/eotg-winter2026.jpg",
    link: "https://www.eotgatucsd.com ",
  },
  {
    name: "Tapioca Express Fundraiser",
    date: "November 21st, 2025",
    location: "Tapioca Express, Price Center",
    tags: ["Fundraiser", "Finance"],
    image: "/event-logos/tapex_fundraiser.jpg",
    link: "https://tapiocaexpress.com/",
  },
  {
    name: "Board Game Night",
    date: "November 21st, 2025",
    location: "Study Rooms, Price Center",
    tags: ["Social"],
    image: "/event-logos/BoardGameNightPostWLogos.jpg",
    link: "",
  },
  {
    name: "DECaF Fall 2025",
    date: "October 14th, 2025",
    location: "Qualcomm Room, JSOE",
    tags: ["Career"],
    image: "/event-logos/DECaF_FA25.jpg",
    link: "https://decafucsd.com",
  },
  {
    name: "Sunset & S'mores Bonfire Night",
    date: "October 3rd, 2025",
    location: "La Jolla Shores",
    tags: ["Social"],
    image: "/event-logos/Sunset__Smores_Bonfire.png",
    link: "",
  },
  {
    name: "Intro Night / GBM",
    date: "October 1st, 2025",
    location: "Qualcomm Conference Center",
    tags: ["Social", "GBM"],
    image: "/event-logos/TESC_Intro_Night.png",
    link: "",
  },
  {
    name: "Engineers on the Green",
    date: "September 30th, 2025",
    location: "Warren Mall",
    tags: ["Social", "Career"],
    image: "/event-logos/Fall-2025-EOTG.png",
    link: "https://www.eotgatucsd.com ",
  },
  {
    name: "Engineer's Formal Prom",
    date: "May 18th, 2025",
    location: "Stage Room",
    tags: ["Social"],
    image: "/event-logos/Engineering_Prom_1.jpg",
    link: "https://www.zeffy.com/en-US/ticketing/2025-aerospace-prom",
  },
  {
    name: "Headshot Day & Mixer",
    date: "May 5th, 2025",
    location: "Bear Room, Price Center",
    tags: ["Social", "Career"],
    image: "/event-logos/headshot&mixer.jpg",
    link: "https://tinyurl.com/headshot-mixer",
  },
  {
    name: "ASML Tech Talk",
    date: "April 25th, 2025",
    location: "Qualcomm Conference Center - JSOE 1st Floor",
    tags: ["Career"],
    image: "/event-logos/asml-tech-talk.png",
    link: "https://tinyurl.com/euv-lithography",
  },
  {
    name: "TESC Olympics",
    date: "April 19th, 2025",
    location: "Matthew's Quad",
    tags: ["Social"],
    image: "/event-logos/field_day_2.jpg",
    link: "https://tinyurl.com/sp25-tesc-olympics",
  },
  {
    name: "Tapioca Express Fundraiser",
    date: "March 6th, 2025",
    location: "Tapioca Express, Price Center",
    tags: ["Fundraiser", "Finance"],
    image: "/event-logos/Tapioca.png",
    link: "https://tapiocaexpress.com/",
  },
  {
    name: "Sandcastle Competition",
    date: "March 2nd, 2025",
    location: "La Jolla Shores",
    tags: ["Social"],
    image: "/event-logos/SandcastleBonfire.jpg",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfYP_vwKSgp0AF6B310_VyWz5hGEI3Hg6UfZetKdhE_THPiNA/viewform",
  },
  {
    name: "Talk with Stempad",
    date: "February 7th, 2025",
    location: "Qualcomm Room, JSOE",
    tags: ["Career"],
    image: "/event-logos/stempad-talk-wi25.webp",
    link: "http://tinyurl.com/stempad-rsvp",
  },
  {
    name: "DECaF",
    date: "January 21st, 2025",
    location: "Qualcomm Room, JSOE",
    tags: ["Career"],
    image: "/event-logos/decaf-event-wi25.png",
    link: "https://decafucsd.com",
  },
  {
    name: "Engineers on the Green",
    date: "January 7th, 2025",
    location: "Warren Mall",
    tags: [],
    image: "/event-logos/eotg-event-wi25.jpg",
    link: "https://tescatucsd.org/eotg",
  },
  {
    name: "DECaF",
    date: "October 9th, 2024",
    location: "Qualcomm Room, JSOE",
    tags: ["Career"],
    image: "/event-logos/decaf-event-fa24.jpg",
    link: "https://decafucsd.com",
  },
  {
    name: "Engineers on the Green",
    date: "October 1st, 2024",
    location: "Warren Mall",
    tags: [],
    image: "/event-logos/eotg-event-fa24.jpg",
    link: "https://tescatucsd.org/eotg",
  },
  {
    name: "DECaF",
    date: "November 6th, 2023",
    location: "",
    tags: ["Career"],
    image: "/event-logos/decaf-event-fa23.svg",
    link: "https://decafucsd.com",
  },
  {
    name: "SD Hacks",
    date: "February 19th-21st, 2021",
    location: "",
    tags: ["Hackathon"],
    image: "/event-logos/sd-hacks-event-wi21.png",
    link: "",
  },
  {
    name: "DECaF",
    date: "January 19th-21st, 2021",
    location: "",
    tags: ["Career"],
    image: "/event-logos/decaf-event-wi21.svg",
    link: "https://decafucsd.com",
  },
  {
    name: "Engineers on the Green",
    date: "January 11th-12th, 2021",
    location: "Warren Mall",
    tags: [],
    image: "/event-logos/eotg-event-wi21.svg",
    link: "https://tescatucsd.org/eotg",
  },
  {
    name: "Baking Event",
    date: "December 4th, 2020",
    location: "",
    tags: ["Social"],
    image: "/event-logos/baking-event-fa20.png",
    link: "",
  },
  {
    name: "Matcha",
    date: "November 16th-20th, 2020",
    location: "",
    tags: [],
    image: "/event-logos/matcha-event-fa20.svg",
    link: "",
  },
  {
    name: "Destress with TESC",
    date: "November 11th, 2020",
    location: "",
    tags: ["Social"],
    image: "/event-logos/destress-event-fa20.svg",
    link: "",
  },
  {
    name: "Engineers on the Green",
    date: "October 5th-9th, 2020",
    location: "Warren Mall",
    tags: [],
    image: "/event-logos/eotg-event-fa20.svg",
    link: "https://tescatucsd.org/eotg",
  },
];
