name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Builds tesc.ucsd.edu for deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Set up .env
        env: 
          AIRTABLE_KEY: ${{ secrets.AIRTABLE_READ_ONLY_API_KEY }}
        run: |
          echo "REACT_APP_AIRTABLE_KEY=$AIRTABLE_KEY" > .env
      - name: Build tesc.ucsd.edu
        run: npm install && CI=false npm run build
        shell: bash
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: . # or specify the directory where your build files are located
